
try: # Va a intentar correr este bloque de cÃ³digo, si hay un error ->
    resultado = 10 + 10
    print(resultado)
except: # -> Entonces va a ejecutar esto.
    print('Parece que hay un error, escribe correctamente las variables.')